name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: streetree.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image for frontend
        run: |
          docker build -t streetree.azurecr.io/frontend:latest -f frontend/Dockerfile ./frontend
          docker push streetree.azurecr.io/frontend:latest

      - name: Build and push Docker image for backend
        run: |
          docker build -t streetree.azurecr.io/backend:latest -f backend/Dockerfile ./backend
          docker push streetree.azurecr.io/backend:latest

      - name: Deploy to Azure
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          azd deploy
